version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d
    command: postgres -c ssl=off
volumes:
  db:
    driver: local
