version: "3.8"
services:
  xo:
    image: xo
    volumes:
      - ../player-manager/internal/xo:/xo
    depends_on:
      - db
    command: >
      /bin/bash -c "
        /wait-for-it.sh db:5432 && 
        /xo-generate.sh &&
        exit
      "
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres